name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: python_harga_buku
      id: python_harga_buku
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 8
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON_HARGA_BUKU_RESULTS: "${{steps.python_harga_buku.outputs.result}}"
      with:
        runners: python_harga_buku
